### ISSUE TITLE
Confusion between .trg and .vmrk files?

### ISSUE THREAD

**Issue by ZviBaratz** [DalPsychNeuro/NESC_3505_textbook#15]
Hi,

Thank you so much for your incredible work on this book! It is a really great resource. 
I noticed that in [importing EEG data with MNE](https://neuraldatascience.io/7-eeg/mne_data.html#import-raw-data) section there are two references to `.trg` files, which are not previously mentioned. From context, it seems like these should be replaced with `.vmrk`. Just thought this would be an easy fix and hopefully save some confusion.

**Comment by aaronjnewman** [comment]
Thanks for the kind words and for catching that error! .trg files are for a different file format. You're correct that the references should've been to .vmrk files and I've corrected the book. Thanks again!
